#define _file_input					1
#define _NEWLINE_OR_stmt_seq				2
#define _stmt						3
#define _funcdef					4
#define _NAME_DUNDER					5
#define _parameters					6
#define _test						7
#define _suite						8
#define _typedargslist					9
#define _poskeyword_args_kwonly_kwargs			10
#define _args 						11
#define _kwonly_kwargs					12
#define _kwargs						13
#define _argument					14
#define _COMMA_argument_seq				15
#define _tfpdef						16
#define _simple_stmt					17
#define _compound_stmt					18
#define _small_stmt					19
#define _SEMICOLON_small_stmt_seq			20
#define _expr_stmt					21
#define _flow_stmt					22
#define _testlist_star_expr				23
#define _annassign					24
#define _augassign					25
#define _testlist					26
#define _EQUAL_testlist_star_expr_seq			27
#define _test_OR_star_expr				28
#define _COMMA_test_OR_star_expr_seq			29
#define _return_stmt					30
#define _if_stmt 					31
#define _while_stmt					32
#define _for_stmt					33
#define _classdef					34
#define _ENCS_seq					35
#define _exprlist					36
#define _stmt_seq					37
#define _or_test					38
#define _and_test					39
#define _OR_and_test_seq				40
#define _AND_not_test_seq				41
#define _not_test					42
#define _comparison					43
#define _expr						44
#define _comp_op_expr_seq				45
#define _comp_op					46
#define _star_expr					47
#define _xor_expr					48
#define _VBAR_xor_expr_seq				49
#define _and_expr					50
#define _CIRCUMFLEX_and_expr_seq			51
#define _shift_expr					52
#define _AMPER_shift_expr_seq				53
#define _arith_expr					54
#define _SHIFT_arith_expr_seq				55
#define _PLUS_MIN_term_seq				56
#define _term						57
#define _factor						58
#define _opr_factor_seq					59
#define _power						60
#define _atom_expr					61
#define _atom						62
#define _trailer_seq					63
#define _trailer					64
#define _testlist_comp					65
#define _STRING_seq					66
#define _cntsc_production				67
#define _comp_for					68
#define _cns_seq					69
#define _arglist					70
#define _subscriptlist					71
#define _subscript					72
#define _COMMA_subsc_seq				73
#define _sliceop					74
#define _expr_OR_star_expr				75
#define _COMMA_expr_OR_star_expr_seq			76
#define _COMMA_test_seq					77
#define _argument_arglist				78
#define _COMMA_argument_arglist_seq			79
#define _comp_iter					80
#define _comp_if					81
#define _sync_comp_for					82
#define _test_nocond					83
